# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dae81ea29bcff12a543da671922c7342f95bccd26dec4bbc54366e2ca143684e0f2502fcca390d7734af913c019e13863cbc7b692ca44887953f10633e23727

test:
  secret_key_base: 9968b8586dab0305d4745083335c421098e7da31d7514a9785e59e147c7beafb0d4a90201d589d0836c5b15ab362883ddbe371da1c90e061cb19a90c56fbbffe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
